name: Docker Build and Push
 
on:
  push:
    branches: [ main ]  # 触发分支，可以根据需要修改
  pull_request:
    branches: [ main ] # 同上，可以根据需要修改
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }} # Docker Hub 用户名
        password: ${{ secrets.DOCKERHUB_TOKEN }}   # Docker Hub 访问令牌（不是密码）
        
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: . # Dockerfile 的路径，默认为当前目录。如果有特定路径，请修改这里。
        file: ./Dockerfile # Dockerfile 的名称，如果与默认文件名相同可以省略。
        push: true # 是否推送到 Docker Hub，默认为 false。
        tags: yourusername/yourimage:latest # 你的 Docker Hub 用户名和镜像名及标签。
