name: Docker Image CI

on:
  push:
    branches: [ "main" ] # 触发条件，例如推送到主分支
    tags: ['v*'] # 或者，推送到带有 v 开头的 tag
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 # 检出代码

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_REGISTRY }}:${{ github.ref_name }} # 使用 tag 作为镜像 tag
